# Generated by Django 3.0.5 on 2020-08-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_users',
            old_name='rating',
            new_name='rankCount',
        ),
        migrations.RemoveField(
            model_name='all_users',
            name='handle',
        ),
        migrations.AddField(
            model_name='all_users',
            name='rank',
            field=models.CharField(default='great', max_length=60),
        ),
    ]
