# Generated by Django 3.0.5 on 2020-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_educational'),
    ]

    operations = [
        migrations.CreateModel(
            name='Div_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Div_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Div_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.IntegerField()),
            ],
        ),
    ]
