# Generated by Django 3.1 on 2020-09-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_div_1_div_2_div_3_global_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='div_1',
            name='problemList',
            field=models.CharField(default='A ', max_length=100),
        ),
        migrations.AddField(
            model_name='div_2',
            name='problemList',
            field=models.CharField(default='A ', max_length=100),
        ),
        migrations.AddField(
            model_name='div_3',
            name='problemList',
            field=models.CharField(default='A ', max_length=100),
        ),
        migrations.AddField(
            model_name='educational',
            name='problemList',
            field=models.CharField(default='A ', max_length=100),
        ),
        migrations.AddField(
            model_name='global',
            name='problemList',
            field=models.CharField(default='A ', max_length=100),
        ),
        migrations.AddField(
            model_name='others',
            name='problemList',
            field=models.CharField(default='A ', max_length=100),
        ),
    ]
