# Generated by Django 3.1 on 2020-09-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_auto_20200920_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='div_1',
            name='contestName',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AddField(
            model_name='div_2',
            name='contestName',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AddField(
            model_name='div_3',
            name='contestName',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AddField(
            model_name='educational',
            name='contestName',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AddField(
            model_name='global',
            name='contestName',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AddField(
            model_name='others',
            name='contestName',
            field=models.CharField(default='----', max_length=100),
        ),
    ]
